pkg/module/errors.go
pkg/module/middleware.go
pkg/module/transport.go

Return a proper response when the key is invalid.
Instead of 500 we now respond with a 401.

fix(middleware): adjust invalid key response

---

README.md
internal/cli/uploadcmd/archive.go
internal/cli/uploadcmd/upload.go
pkg/module/errors.go
pkg/module/middleware.go
pkg/module/transport.go

With `-recursive=false` the upload will only handle the given directory and not walk the whole directory tree looking for `boring-registry.hcl` files.
With `-ignore-existing=false` the upload will fail if a module version already exists in a specific version and exit with error code 1 . This is useful in combination with `-recursive=false` to get an indication if the module version has changed.

ignore existing modules, recursive flag

---

README.md
internal/cli/uploadcmd/archive.go
internal/cli/uploadcmd/upload.go
pkg/module/parser.go

This PR adds a `-version-constraints` subcommand to the upload subcommand. Its intention is to fix #6 .
Let me know if there is a better place in the code for this functionality - I was thinking a lot about it but am not entirely happy about it...
Also let me know if I should a dedicated section in the `README.md`.
Thanks!

Add -version-constraints flag to upload subcommand

---

.github/workflows/go.yml
.github/workflows/goreleaser.yml
Dockerfile
go.mod

This PR intends to change the go version to the latest stable version

build: bump go to 1.16

---

.github/workflows/container.yml

This commit should help to prevent #12 from happening again.
By building and pushing the container image we can make sure that releases actually build for our users. 
If we want to build images for every commit at some point, we should merge that github actions workflow with the `go.yml` workflow

ci: build container image for releases and push to ghcr

---

cmd/root.go
cmd/server.go
pkg/auth/auth.go
pkg/provider/collection.go
pkg/provider/endpoint.go
pkg/provider/errors.go
pkg/provider/middleware.go
pkg/provider/provider.go
pkg/provider/provider_test.go
pkg/provider/service.go
pkg/provider/storage.go
pkg/provider/storage_gcs.go
pkg/provider/storage_s3.go
pkg/provider/transport.go

This changeset adds support for the Provider Registry Protocol and it unfortunately, comes with a breaking change ⚠️ :
* `--storage-s3-prefix` & `--storage-gcs-prefix` is now extended with: `${prefix}/providers` & `${prefix}/modules`. 
Example tree:
```
bucket
├── modules
│   └── namespace=tier
│       └── name=test
│           └── provider=test
│               └── version=1.0.0
└── providers
└── namespace=tier
└── name=test
└── version=1.0.0
```
Will follow up with more fixes and documentation around this but this should lay the groundwork 🙂

Add Provider Protocol support

---

pkg/core/provider.go
pkg/core/provider_test.go

This PR include infrastructure code necessary to start refactoring the existing code and prepare for #22
It contains the `Provider` struct, its associated data types and their methods.

feat(core): add package for core data types and their methods

---

cmd/root.go
pkg/provider/storage_gcs.go

Hey y'all! 
First off I want to say thank you so much for putting this together, this has saved me god knows how many hours!
This PR adds support for using googleapi URLs for GCS objects instead of creating signed URLs. We have a use case for a provider that's published on a public bucket, so the additional perms for blob signing were not needed. One thing to call out is that this is a breaking change, as users that rely on blob signing will need to specify `--storage-gcs-signedurl=true` to maintain the current behavior. However, to maintain compatibility the default for providers could be set to true unless explicitly specified to be false.

Adds support for using gcs API URLs for provider URLs

---

README.md

This may help save some time for people wondering about an official Docker image (such as in https://github.com/TierMobility/boring-registry/issues/27).

Add note about location of Docker image

---

cmd/migrate.go
pkg/module/storage.go
pkg/module/storage_inmem.go
pkg/storage/gcs.go
pkg/storage/path.go
pkg/storage/path_test.go
pkg/storage/s3.go

This PR is based on  #38 . Don't merge until that PR is merged and this PR is rebased. 
Adds a `migrate` subcommand that copies existing modules into the correct storage layout for `v0.8.0`.
Check commit 965a126ffe2d8e4e47587774adab3dc129972430 for the changes.

Add migration subcommand for modules

---

cmd/migrate.go
pkg/provider/storage.go
pkg/storage/gcs.go
pkg/storage/path.go
pkg/storage/s3.go

* Support migration of providers from `0.7.0` to `0.8.0`
* Provider `zip` archives, `SHA256SUM`,`SHA256SUM.sig` and `signing-keys.json` are copied as-is

feat(migrate): support provider migration

---

cmd/root.go
cmd/server.go
pkg/storage/gcs.go
pkg/storage/s3.go

This PR implements #45.
We're not quite consistent on our usage of presigned URLs right now. As providers can only be served with presigned URL, it's currently not sensible to run boring-registry publicly without authentication/authorization anways. Thus we should be safe to use presigned URLs everywhere

feat(storage): use only presigned URLs

---

cmd/upload.go

Fixes #98 
Don't display usage on errors during upload. The error message is enough.

to suppress usage output on upload errors 

---

README.md
pkg/storage/gcs.go
pkg/storage/path.go
pkg/storage/s3.go
pkg/storage/s3_test.go
pkg/storage/storage.go

Currently, users have to specify a `signing-keys.json` for the providers within the namespace with a single GPG public key:
```json
{
"key_id": "51852D87348FFC4C",
"ascii_armor": "-----BEGIN PGP PUBLIC KEY BLOCK-----\nVersion: GnuPG v1\n...",
"trust_signature": "",
"source": "HashiCorp",
"source_url": "https://www.hashicorp.com/security.html"
}
```
This approach doesn't allow users to specify multiple signing keys. This would for example be useful if the corresponding private key is lost or rotated. Since new provider binaries would have to be signed with another private key, users would have to  rebuild/recompute all signatures for all provider versions.
This PR adds support for a `signing-keys.json` with the following structure:
```json
{
"gpg_public_keys": [
{
"key_id": …
```

feat(storage): support using multiple GPGPublicKeys for providers

---

cmd/archive.go
cmd/server.go
cmd/upload.go
go.mod
go.sum
pkg/auth/provider_okta.go
pkg/mirror/transport.go
pkg/module/storage_inmem.go
pkg/module/transport.go
pkg/provider/transport.go
pkg/storage/gcs.go
pkg/storage/s3.go
pkg/storage/s3_test.go

The package is unmaintained, we should probably try to get rid of it

refactor: replace github.com/pkg/errors with stdlib errors package

---

.github/workflows/release.yml

Disable the broken CI step that was previously skipped for the last years. Unblocks the pipeline for #165

ci: disable broken helm lint job

---

cmd/upload.go

Hello guys 👋
My SHA256SUMS also contains a sha for the manifest.json :  
But when i try to upload my provider, sha validation fail because of the json file (which have a valid sha by the way):  
So i've just added the json extension in the regex (instead of allowing all type of files).

:bug: Validate SHA sum for JSON manifest file

---

cmd/upload.go

`boring-registry upload` is an alias for the `boring-registry upload module` command. Unfortunately, the flags from `upload` were not available to `upload module`.
This PR attaches the flags to a persistent flagset, so that the child command inherits the flags from the parent properly.

fix(upload): upload module inherits flags from upload

---

cmd/server.go
go.mod
go.sum
pkg/mirror/endpoint.go
pkg/mirror/transport.go
pkg/module/endpoint.go
pkg/module/transport.go
pkg/observability/metrics.go
pkg/observability/middleware.go
pkg/provider/endpoint.go
pkg/provider/transport.go
vendor/github.com/prometheus/client_golang/prometheus/promauto/auto.go
vendor/github.com/prometheus/common/expfmt/decode.go
vendor/github.com/prometheus/common/expfmt/encode.go
vendor/github.com/prometheus/common/expfmt/expfmt.go
vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
vendor/github.com/prometheus/common/expfmt/text_create.go
vendor/github.com/prometheus/common/model/labels.go
vendor/github.com/prometheus/common/model/metric.go
vendor/modules.txt

It add custom new metrics to the `/metrics` endpoint.
It adds 3 metrics dédicated to boring : 
|Name|Type|Description|Labels|
|---|---|---|---|
|boring_registry_providers_list_versions|counter|Number of boring's providers versions listing.|namespace, name|
|boring_registry_providers_download_version|counter|Number of boring's providers download.|namespace, name, version, os, arch|
|boring_registry_modules_list_versions|counter|Number of boring's modules versions listing.|namespace, name, provider|
|boring_registry_modules_download_version|counter|Number of boring's modules download.|namespace, name, provider, version|
|boring_registry_mirrors_list_provider_versions|counter|Number providers versions listing on the mirror.|hostname, namespace, name| …

feat: Adding more metrics

---

README.md

While reading the doc I found a link pointing to the version 0.14.0 that the documentation website do not contains 😅

doc: Invalid URL to the Helm documentation

---

cmd/archive.go
cmd/archive_test.go

This PR fixes #182, which occurs when uploading a module non-recursively with `boring-registry upload <omitted> .`

fix(upload): fix archive file header name when uploading current dir

---

pkg/discovery/remote_service_discovery.go

Adds more debug information for https://github.com/boring-registry/boring-registry/issues/195

fix(discovery): detailed URL when well-known endpoint discovery fails

---

helm/boring-registry/templates/server-deployment.yaml
helm/boring-registry/values.yaml

Adding this feature allows us to mount secrets into the pod using CSI driver in k8s.
https://secrets-store-csi-driver.sigs.k8s.io/topics/sync-as-kubernetes-secret 
This is especially needed to provide API keys in an existing secret mounted by an external secrets provider.

feat: Add possibility to configure volumes

---

helm/boring-registry/Chart.yaml
helm/boring-registry/templates/server-deployment.yaml

Fix a issue where settings `.server.storage.s3.pathStyle` to `"true"` would result in a bool instead of a string, effectively making it impossible to enable s3 with pathStyle

[helm] Escape environment variables values

---

helm/boring-registry/templates/server-hpa.yaml

autoscaling/v2beta1 is deprecated

helm: use autoscaling/v2 version for hpa

---

cmd/server.go
pkg/discovery/discovery.go

This is a fix for #215 which was accidentally introduced in `v0.16.0` and prevents running the server without configuring OIDC.

fix(server): check for oidc or okta auth when validating login

---

helm/boring-registry/templates/cache-config.yaml
helm/boring-registry/templates/server-deployment.yaml
helm/boring-registry/values.yaml

Configures the Pod created in the helm chart to comply with the Restricted Pod Security Standard.
https://kubernetes.io/docs/concepts/security/pod-security-standards/

feat(helm): Enhance default security configuration in helm chart

---

pkg/auth/auth.go
pkg/auth/auth_test.go
pkg/auth/provider.go
pkg/auth/provider_oidc.go

Fixes the bug reported in #228. Previously, the middleware aborted and returned an error on the first error returned by a provider. If multiple providers are configured, it could happen that another provider instance rejected the token and we never actually attempted to verify with the correct provider
Fixes #228

fix(auth): continue token verification if first provider has failed to verify

---

.gitignore
.goreleaser.yml

Got the following error:
```
⨯ build failed after 23s
error=
│ build failed: exit status 1: # go.opentelemetry.io/auto/sdk
│ vendor/go.opentelemetry.io/auto/sdk/tracer.go:88:38: math.MaxUint32 (untyped int constant 4294967295) overflows int
│ vendor/go.opentelemetry.io/auto/sdk/tracer.go:93:38: math.MaxUint32 (untyped int constant 4294967295) overflows int
target=windows_arm_6
```

chore(goreleaser): remove 32bit architectures
