internal/cli/servercmd/server.go
Adding support for TLS to ease development since Terraform requires TLS.
=> server: add support for ListenAndServeTLS

cmd/archive.go, cmd/root.go, cmd/server.go, cmd/upload.go, pkg/module/errors.go, pkg/module/helper.go, pkg/module/middleware.go, pkg/module/service.go, pkg/module/service_test.go, pkg/module/storage.go, pkg/module/storage_gcs.go, pkg/module/storage_inmem.go, pkg/module/storage_s3.go
This changeset changes the previous interface `Registry` to `Storage`.
This name better reflects the purpose of this interface.
=> Module Storage Interface

cmd/server.go, pkg/module/transport.go
Adjusting mux and transport a bit to make it more flexible for future use-cases.
=> module: adjust transport

cmd/server.go
Fix to make sure that we always cancel.
=> cmd/server: ensure cancellation

helm/boring-registry/.helmignore, helm/boring-registry/Chart.yaml, helm/boring-registry/templates/_helpers.tpl, helm/boring-registry/templates/server-deployment.yaml, helm/boring-registry/templates/server-hpa.yaml, helm/boring-registry/templates/server-ingress.yaml, helm/boring-registry/templates/server-secret.yaml, helm/boring-registry/templates/server-service.yaml, helm/boring-registry/templates/server-serviceaccount.yaml, helm/boring-registry/values.yaml
This adds an example helm chart that can be used to get up and running with the boring registry.
=> Add example Helm chart

.github/workflows/go.yml
Figured this might be useful but don't have strong feelings on the matter; feel free to close if it's not something this project needs.
=> Add GitHub action for code formatting

helm/boring-registry/Chart.yaml, helm/boring-registry/templates/server-deployment.yaml, helm/boring-registry/values.yaml
A little change i need in order to configure env variables for secrets :)
=> feat(helm): add extraEnv for additional environment variables

pkg/storage/s3.go
* Construct download URLs from presigned URLs. This should hopefully prevent us from generating invalid URLs, for example for edge-cases like `us-east-1`.
* Non-presigned-URLs for S3 are prefixed with `s3::` to explicitely use AWS-authentication with the built-in S3 client in Terraform
=> feat(s3): use the s3:: prefix for download URLs

pkg/auth/auth.go
In v0.7.0, it was allowed to run boring-registry without authentication.
This commit intends to revert to the previous behavior.
=> fix(auth): skip auth checks if no providers are configured

cmd/archive.go, cmd/root.go, pkg/auth/auth.go, pkg/auth/auth_test.go, pkg/module/service_test.go, pkg/storage/s3.go, version/version.go
A lot of small things highlighted by linters. Let's have a look at them at some point :)
=> chore: fix some go lint warnings

README.md
I posted this PR for visibilty only. It should contain the changes we want to make to the `README.md` for `v0.8.0` and should only be merged shortly before cutting the release.
Feel free to push additional commits to this branch!
=> docs(README): documentation for v0.8

README.md, cmd/server.go, pkg/auth/provider_static.go, pkg/auth/provider_static_test.go
=> feat(auth): allow passing multiple static auth tokens with env variable

cmd/upload.go
This is a small PR that prepares the introduction of a `upload provider` subcommand.
=> refactor(upload): move module upload to subcommand of upload

.github/workflows/container.yml
This PR addresses #170 to build `amd64` and `arm64` images
=> ci: support building multi-arch images

pkg/mirror/copier.go
Logging in case there is no error lead to a panic
=> fix(mirror): dereferencing nil if there is no error while logging

helm/boring-registry-dashboard.json
I thought I'd share the Grafana dashboard I've been using for this project. It's not pretty, but I thought I'd get it out here so that people can improve on it
=> feat: add Grafana dashboard

docs/requirements.txt
The packages had conflicting dependencies
=> ci: fix building and publishing docs

pkg/core/proxifier.go, pkg/core/proxifier_test.go, pkg/module/transport.go, pkg/provider/transport.go
This PR relates to https://github.com/boring-registry/boring-registry/issues/192
=> fix(download-proxy): Enhance the way proxy URL are managed

docs/configuration/caching-proxy.md, helm/boring-registry/Chart.yaml, helm/boring-registry/templates/cache_config.yaml, helm/boring-registry/templates/server-deployment.yaml, helm/boring-registry/templates/server-service.yaml, helm/boring-registry/values.yaml
to relieve S3 (in our case) a bit from stress, we cache queries via nginx
This is still WIP, I'll check in next week after we have this running for some time.
=> Using nginx as a caching proxy

cmd/server.go
This PR fixes #219. An "empty" struct was added by mistake to the list of auth providers, which prohibited API access without authentication configured.
=> fix(auth): do not add empty provider when no auth is configured #219

cmd/root.go, docs/configuration/storage-backends/aws-s3.md, helm/boring-registry/templates/server-deployment.yaml, helm/boring-registry/values.yaml, pkg/storage/s3.go
This relates to https://github.com/boring-registry/boring-registry/issues/226
This PR will stay "draft" untill discussions with the maintainers on the related issue have been validated
=> feat: Add option to control AWS client log mode

pkg/auth/provider_static.go, pkg/auth/provider_static_test.go
* modernizing code with new Go standard library features
* Test coverage for the static provider's verify method
=> test(auth): refactoring and additional tests
